apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fwqkw0lpn-nodejs 
  janus-idp.io/tekton: fwqkw0lpn-nodejs
  backstage.io/kubernetes-id: fwqkw0lpn-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fwqkw0lpn-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  