apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fwqkw0lpn-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fwqkw0lpn-nodejs 
  name: fwqkw0lpn-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: fwqkw0lpn-nodejs 
